package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/otterlab-bio/otter/internal/assets"
	"github.com/otterlab-bio/otter/internal/logger"
	"github.com/otterlab-bio/otter/internal/projectlayout"
	runstate "github.com/otterlab-bio/otter/internal/run"
	"github.com/spf13/cobra"
)

var (
	initLegacyTrack bool // Author the legacy compatibility track instead of canonical v1
	initLegacyRules bool // Use legacy Snakemake rules inside the legacy track
)

// initCmd represents the init command
var initCmd = &cobra.Command{
	Use:   "init [project-name]",
	Short: "Initialize a new otter project",
	Long: `Initialize a new otter project.

By default this writes a canonical v1 project: packaged workflow assets pinned
into workflows/, rules/, environments/, and schemas/, plus a project.lock.yaml
that records their digests. Add project.yaml, samples.tsv, and
references.lock.yaml with "otter create", then resolve a run with
"otter config resolve".

With --legacy it writes the established compatibility project instead: the
beaverflow directory tree with config/otter.yaml generated by
"otter create --legacy" and execution through the explicit Snakemake
compatibility executor.

The two tracks are marked on disk (project.lock.yaml for v1,
.otter/assets.manifest.json for legacy) and later commands refuse to mix them.

Canonical project directories:
  workflows/     # Packaged workflow assets (pinned)
  rules/         # Snakemake compatibility rules (pinned)
  environments/  # Packaged environment declarations (pinned)
  schemas/       # Packaged JSON schemas (pinned)
  runs/          # Immutable run snapshots, created by "otter config resolve"

Legacy compatibility directories (--legacy):
  config/  data/  envs/  inst/  R/  rules/  saveRDS/  temp/  userspace/  www/

Examples:
  otter init my_project                 # canonical v1 project
  otter init my_project --legacy        # legacy compatibility project
  otter init my_project --legacy --legacy-rules`,
	Args: cobra.MaximumNArgs(1),
	RunE: runInit,
}

func init() {
	rootCmd.AddCommand(initCmd)
	initCmd.Flags().BoolVar(&initLegacyTrack, "legacy", false, "Author the legacy compatibility project instead of a canonical v1 project")
	initCmd.Flags().BoolVar(&initLegacyRules, "legacy-rules", false, "With --legacy, copy the legacy rule set instead of the current rootless rules")
}

func runInit(cmd *cobra.Command, args []string) error {
	projectName := "otter-project"
	if len(args) > 0 {
		projectName = args[0]
	}
	projectDir := projectName

	if initLegacyRules && !initLegacyTrack {
		return fmt.Errorf("--legacy-rules only applies to the legacy compatibility track; add --legacy or drop --legacy-rules")
	}
	if _, err := os.Stat(projectDir); err == nil {
		logger.Warnf("Directory %s already exists", projectDir)
	}

	if initLegacyTrack {
		return runInitLegacyTrack(projectName, projectDir)
	}
	return runInitCanonicalTrack(projectName, projectDir)
}

// runInitCanonicalTrack writes a canonical v1 project: pinned assets plus a
// project.lock.yaml that later commands use to prove the project track.
func runInitCanonicalTrack(projectName, projectDir string) error {
	if err := os.MkdirAll(projectDir, 0o755); err != nil {
		return fmt.Errorf("failed to create project directory %s: %w", projectDir, err)
	}
	if existingTrack, err := projectlayout.Detect(projectDir); err != nil {
		return err
	} else if existingTrack == projectlayout.TrackLegacy {
		return fmt.Errorf(
			"%s is already a legacy compatibility project; use `otter init %s --legacy` for that layout, or initialise a new directory",
			projectDir, projectName,
		)
	}

	copier := assets.NewAssetCopier(projectDir, "rootless")

	logger.Info("Creating canonical project directory structure...")
	if err := copier.CreateV1DirectoryStructure(); err != nil {
		return fmt.Errorf("failed to create directory structure: %w", err)
	}

	logger.Info("Pinning packaged workflow assets...")
	copiedSets, err := copier.CopyV1ProjectAssets()
	if err != nil {
		return fmt.Errorf("failed to pin workflow assets: %w", err)
	}

	assetSets := make([]projectlayout.AssetSet, 0, len(copiedSets))
	for _, copiedSet := range copiedSets {
		digest, err := runstate.DigestPaths([]string{copiedSet.DestDir})
		if err != nil {
			return fmt.Errorf("failed to digest pinned assets in %s: %w", copiedSet.DestDir, err)
		}
		assetSets = append(assetSets, projectlayout.AssetSet{
			Role:   copiedSet.Role,
			Source: copiedSet.Source,
			Digest: digest,
			Files:  copiedSet.Files,
		})
	}

	lockPath, err := projectlayout.WriteProjectLock(projectDir, projectlayout.ProjectLock{
		ProjectID: projectName,
		Assets:    assetSets,
	})
	if err != nil {
		return err
	}
	logger.Infof("Project lock written: %s", lockPath)

	readmePath := filepath.Join(projectDir, "README.md")
	if err := os.WriteFile(readmePath, []byte(canonicalReadme(projectName)), 0o644); err != nil {
		logger.Warnf("Failed to create README: %v", err)
	}

	checkEnvSupport()

	logger.Info("===========================================")
	logger.Infof("Canonical project '%s' initialized successfully!", projectName)
	logger.Infof("Location: %s", projectDir)
	logger.Info("===========================================")
	logger.Info("Next steps:")
	logger.Info("1. Place paired FASTQ files in a data directory")
	logger.Info("2. Build or select a reference registry release (see docs/reference-registry.md)")
	logger.Infof("3. Create the project: otter create --fastq <fastq-dir> --mode RRBS --reference-root <registry> --reference-primary <id@release>")
	logger.Info("4. Resolve a run:     otter config resolve --project project.yaml --backend local")
	logger.Info("5. Execute:           otter run --config runs/<run-id>/run.yaml --executor craftmake --phase step1")

	return nil
}

// runInitLegacyTrack keeps the established compatibility layout and behaviour.
func runInitLegacyTrack(projectName, projectDir string) error {
	if existingTrack, err := projectlayout.Detect(projectDir); err != nil {
		return err
	} else if existingTrack == projectlayout.TrackV1 {
		return fmt.Errorf(
			"%s is already a canonical v1 project; omit --legacy for that layout, or initialise a new directory",
			projectDir,
		)
	}

	// Determine rules type
	rulesType := "rootless"
	if initLegacyRules {
		rulesType = "legacy"
	}

	// Create asset copier
	copier := assets.NewAssetCopier(projectDir, rulesType)

	// Step 1: Create directory structure
	logger.Info("Creating project directory structure...")
	if err := copier.CreateDirectoryStructure(); err != nil {
		return fmt.Errorf("failed to create directory structure: %w", err)
	}

	// Step 2: Copy all workflow assets
	logger.Info("Copying workflow assets...")
	if err := copier.CopyAll(); err != nil {
		return fmt.Errorf("failed to copy assets: %w", err)
	}

	// Step 3: Create snakefile entry point
	snakefilePath := filepath.Join(projectDir, "snakefile")
	if err := os.WriteFile(snakefilePath, []byte("# Main snakefile entry point\n"), 0644); err != nil {
		logger.Warnf("Failed to create snakefile: %v", err)
	}

	// Step 3.5: Stamp workflow assets manifest (this is the legacy track marker).
	logger.Info("Stamping workflow assets manifest...")
	manifest, err := assets.StampWorkflowAssets(projectDir, buildVersion, buildCommit, buildDate)
	if err != nil {
		return fmt.Errorf("failed to stamp assets manifest: %w", err)
	}
	deprecatedCount := 0
	for _, e := range manifest.Entries {
		if e.Deprecated {
			deprecatedCount++
		}
	}
	if deprecatedCount > 0 {
		logger.Warnf("Deprecated assets detected: %d files under R/ (still verified for integrity)", deprecatedCount)
	}
	logger.Infof("Assets manifest written: %s (%d files)", assets.ManifestPath(projectDir), len(manifest.Entries))

	readmePath := filepath.Join(projectDir, "README.md")
	if err := os.WriteFile(readmePath, []byte(legacyReadme(projectName)), 0o644); err != nil {
		logger.Warnf("Failed to create README: %v", err)
	}

	// Check enva support
	checkEnvSupport()

	// Summary
	logger.Info("===========================================")
	logger.Infof("Project '%s' initialized successfully (legacy compatibility track)!", projectName)
	logger.Infof("Location: %s", projectDir)
	logger.Info("===========================================")
	logger.Info("Next steps:")
	logger.Info("1. Copy FASTQ files to data/")
	logger.Info("2. Place pdata file (Excel/CSV) in data/")
	logger.Info("3. Download reference genomes (legacy archive; no checksums or release label):")
	logger.Info("   Visit: https://huggingface.co/datasets/Genomiclab/xdxtools-genomes/tree/main")
	logger.Info("   Download and extract genomes to inst/ directory")
	logger.Info("   This is the pre-contract archive. The canonical track locks a registry")
	logger.Info("   release digest instead of extracting an archive (docs/reference-registry.md).")
	logger.Infof("4. Create config: otter create --legacy --fastq data --output %s/userspace --jobid demo_run", projectName)
	logger.Infof("5. Run workflow: otter run --config %s/userspace/demo_run/config/otter.yaml --executor snakemake", projectName)

	return nil
}

func canonicalReadme(projectName string) string {
	return fmt.Sprintf(`# %s

This is a canonical otter v1 project.

## Directory structure

- workflows/     - Packaged workflow assets, pinned and digested
- rules/         - Snakemake compatibility rules, pinned and digested
- environments/  - Packaged environment declarations, pinned and digested
- schemas/       - Packaged JSON schemas, pinned and digested
- runs/          - One immutable run.yaml snapshot per resolved run
- project.lock.yaml - Track marker and pinned asset digests

## Usage

1. Place paired FASTQ files in a data directory.
2. Build or select a reference registry release (see docs/reference-registry.md).
3. Create the project intent:

   otter create --fastq <fastq-dir> --mode RRBS \
     --reference-root <registry-root> --reference-primary <id@release>

4. Validate and resolve an immutable run:

   otter config validate --config project.yaml --schema v1
   otter config resolve --project project.yaml --backend local

5. Execute the resolved snapshot:

   otter run --config runs/<run-id>/run.yaml \
     --executor craftmake --phase step1 --backend local

Reference genomes are never copied into the project. The project locks logical
reference ids and release digests; the registry supplies the bytes.
`, projectName)
}

func legacyReadme(projectName string) string {
	return fmt.Sprintf(`# %s

This is a legacy otter compatibility project.

## Directory structure

- config/          - Configuration files
- data/            - Input data (FASTQ files, pdata)
- envs/            - Conda environments (copied from package)
- inst/            - Genome reference files
- R/               - R/Python scripts
- rules/           - Snakemake rules
- saveRDS/         - R intermediate results
- temp/            - Temporary files
- userspace/       - User workspace
- www/             - Web resources
- *.snakemake      - Snakemake workflow files

## Usage

1. Copy your FASTQ files to data/
2. Place your pdata file (Excel/CSV) in data/
3. Download reference genomes (legacy archive; no checksums or release label):
   - Visit: https://huggingface.co/datasets/Genomiclab/xdxtools-genomes/tree/main
   - Download and extract genomes to inst/ directory
   - This is the pre-contract legacy archive. The canonical track instead locks a
     registry release digest and never copies genomes into the project; see
     docs/reference-registry.md.
4. Create config file: otter create --legacy --fastq data --output %s/userspace --jobid demo_run
5. Run workflow: otter run --config %s/userspace/demo_run/config/otter.yaml --executor snakemake

## Snakemake workflows

Available workflows:
- BeaverBS_step1/2/3.snakemake   - RRBS/WGBS bisulfite sequencing
- BeaverPDX_step1/2/3.snakemake  - PDX bisulfite sequencing
- BeaverRNA_step1/2.snakemake    - RNA-seq analysis
- BeaverRNASEQPDX_step1/2/3.snakemake - PDX RNA-seq analysis
`, projectName, projectName, projectName)
}

// checkEnvSupport checks if enva is available and provides installation guidance
func checkEnvSupport() {
	logger.Info("")
	logger.Info("Checking package manager support...")

	if _, err := exec.LookPath("enva"); err != nil {
		// enva not found
		logger.Warn("────────────────────────────────────────────────────────")
		logger.Warn("enva not found in PATH")
		logger.Warn("")
		logger.Warn("For the best environment workflow, install enva:")
		logger.Warn("  enva is rattler-first and can interoperate with existing conda/mamba/micromamba environments")
		logger.Warn("")
		logger.Warn("Installation:")
		logger.Warn("  wget https://github.com/otterlab-bio/enva/releases/latest/download/enva-linux-x86_64")
		logger.Warn("  chmod +x enva-linux-x86_64")
		logger.Warn("  sudo mv enva-linux-x86_64 /usr/local/bin/enva")
		logger.Warn("")
		logger.Warn("Or build from source:")
		logger.Warn("  git clone https://github.com/otterlab-bio/enva")
		logger.Warn("  cd enva && cargo build --release")
		logger.Warn("  cp target/release/enva /usr/local/bin/enva")
		logger.Warn("")
		logger.Warn("Falling back to conda run (slower)")
		logger.Warn("────────────────────────────────────────────────────────")
	} else {
		// enva found
		logger.Info("✓ enva detected - rattler-first environment management is available")
		logger.Info("")
	}
}
